//ARQUIVO COM AS CHAVES DE ACESSO AS APIs DOS PROVEDORES HOMOLOGADO
//UTILIZADO NA UNIT IPGeoLocation.Providers.xxxx, ASSIM EVITANDO QUE SEJA INFORMADO NO CÓDIGO FONTE

const
  APIKey_IPInfo='';
  APIKey_IPGeoLocation='';
  APIKey_IP2Location='';
  APIKey_IPAPI='';
  APIKey_IPStack='';
  APIKey_IPIfy='';
  APIKey_IPGeolocationAPI=''; //FULL FREE
  APIKey_IPData='';
  APIKey_IPWhois=''; //FULL FREE
  APIKey_IPDig=''; //FULL FREE
  APIKey_IPTwist='';
  APIKey_IPLabstack='';
  APIKey_IP_API=''; //FULL FREE
  APIKey_DB_IP='free';
